<template>
  <div class="tool-page flex flex-direction align-center justify-center padding">
    <van-button round class="bg-primary font-bold size-72 margin-bottom" @click="importAllLang">Import</van-button>
    <van-button round class="bg-blue fc-fff font-bold size-72 margin-bottom" @click="getAllLang">Get</van-button>
    <van-button round class="bg-error fc-fff font-bold size-72 margin-bottom" @click="updateLang">Update</van-button>
  </div>
</template>

<script>
import {Button} from "vant";
import {importAll} from "../plugins/importLang";
import {Toast} from "mand-mobile";

export default {
  components: {
    [Button.name]: Button
  },
  methods: {
    importAllLang() {
      importAll()
    },
    getAllLang() {
      this.$http.get('v1/getLangList',{
        params: {
          local: 'EN',
        }
      })
        .then(res=>{
          console.log(JSON.stringify(res))
        })
        .catch(err=>{
          Toast.failed(err.data.message)
        })
    },
    updateLang() {
      let lang_map = JSON.parse(`{
  "SIGN_UP_AND_GET_MONEY_NOW": "Reg now to receive money for free for 100 years",
  "NICK_NAME": "Nickname",
  "ENTER_NICK_NAME": "Please enter the nickname",
  "RANDOM": "Random",
  "PHONE": "Telephone Number",
  "ENTER_PHONE": "Please enter the telephone number",
  "VERIFY_CODE": "Verification code",
  "ENTER_VERIFY_CODE": "Please enter the verification code",
  "SEND": "Send",
  "PASSWORD": "Password",
  "ENTER_PASSWORD": "Please enter the password",
  "PASSWORD_AGAIN": "Confirm the password",
  "ENTER_PASSWORD_AGAIN": "Please enter the confirmation password",
  "REFERRAL_CODE": "Referral code",
  "ENTER_REFERRAL_CODE": "Please enter the referral code",
  "SIGN_UP": "Sign up",
  "HAS_ACCOUNT_SIGN_IN": "Already member? log in",
  "SIGN_IN": "Sign in",
  "TASK_NUM": "Assignment num",
  "DAY_PROFIT": "Daily earnings",
  "YEAR_PROFIT": "Annual earnings",
  "PROMOTE_COMMISSION": "Reward",
  "REST": "The remaining",
  "NOT_LIMIT": "Unlimited",
  "FINISH_TASK": "Continue",
  "DO_AGAIN": "Take again",
  "RECEIVE_TASK": "Start now",
  "WELCOME_TO_PROMOTE_PLATFORM": "Welcome to the national assignment platform",
  "SHARE_AD_EVERY_DAY_CAN_MAKE_MONEY": "The world's major bands are gathered here,taking the assignment for 5 minutes a day.Enjoy the qualifications to receive endorsement fees for 100 years for free.Start your journey as an ambassador now!",
  "GET_FIRST_AWARD_NOW": "Start the first commission",
  "FREE_GET_MONEY": "Receive money for free",
  "YEAR": "Year",
  "START_SHARE_MAKE_MONEY": "Start sharing to make money now",
  "FREE_GET_MONEY_NOW": "Become a spokesperson now",
  "CLICK_BTN_AUTO_COPY": "Click the button to automatically copy the sharing link",
  "COPY": "Copy",
  "CLICK_ICON_SHARE_FRIEND": "Click the icon below to share it with your friends",
  "CANCEL": "Cancel",
  "LOADING": "Loading...",
  "LOAD_FAILED": "Load failed",
  "NO_MORE": "No more",
  "CLEAR_ALL_NOTIFY": "Clear all notifications",
  "SURE": "Sure",
  "SUCCESS_WITHDRAW_N": "Withdrawal {0} successfully",
  "INVITED_SOMEONE": "Invited {0}",
  "GETTED_N_GIVE": "Got {0} reward money",
  "DEPOSIT_N_BALANCE": "Deposited {0}",
  "GETTED_N_PROFIT": "You've got {0} profit",
  "GETTED_N_AWARD": "You've got {0} assignment income",
  "OTHER_QUESTION_CONTACT_CS": "Other questions? Contact us",
  "DEPOSIT_SUCCESS": "Deposit successfully",
  "DEPOSIT_N_CASH_ARRIVED": "Your Deposited {0} has been arrived!",
  "DO_TASK_MAKE_MONEY": "Take assignments to make money now",
  "BUY_VIP": "Become VIP",
  "YESTERDAY_PROFIT_NOTIFY": "Yesterday's earnings notice",
  "YOU_GOT_COMMISSION_YESTERDAY": "You got a commission yesterday",
  "DO_TASK_GET_MORE_AWARD": "Take assignments to get more reward",
  "AD_TASK_AWARD_ARRIVED": "Congratulations on getting the assignment reward",
  "COMMISSION_HAS_ARRIVED": "Commission has arrived",
  "GET_MORE_AWARD": "Get more income",
  "CAN_NOT_GET_COMMISSION": "Can't get income",
  "CONGRATULATIONS_YOU_GOT_COMMISSION": "You have got income",
  "YOUR_FRIEND_FINISH_TASK_LEVEL": "The assignment level that your level {0} friend {1} completed",
  "YOU_CAN_GET_COMMISSION": "You can get a reward",
  "BECAUSE_YOU_DO_NOT_BUY_VIP": "Because you didn't be a VIP",
  "SO_YOU_CANNOT_GOT_IT": "You can not get a reward",
  "YOUR_FRIEND_FINISH_TASK": "Your level {0} friend {1} complete the mission",
  "CONGRATULATIONS_YOU_GOT": "Congratulations, You've got ",
  "BECAUSE_YOUR_VIP_LEVEL_IS": "Because your VIP level is",
  "SO_YOU_ONLY_GET": "You can only get",
  "BUY_VIP_GET_ALL_COMMISSION": "Be a VIP to receive rewards",
  "UPGRADE_VIP_GET_ALL_COMMISSION": "Upgrade VIP to receive all rewards",
  "TRANSFER_FAILED": "Transfer failed",
  "VIEW_DETAIL": "View detials",
  "COMMISSION_ARRIVED_NOTIFY": "Reward arrival notification",
  "YOUR_FRIEND_BUY_VIP_SPEND": "Your level {0} friend spent money buying VIP",
  "BECAUSE_YOU_BUY_VIP_SPEND": "You spent a total of money on VIP",
  "UPGRADE_VIP": "Upgrade VIP",
  "INVITE_FRIEND_GET_MORE_AWARD": "Invite friends to get more rewards",
  "AWARD_RULE": "Reward rules",
  "LOGIN": "Login",
  "HOME": "Home",
  "VIP": "VIP",
  "MESSAGE": "Notification",
  "MY": "My",
  "TAB_MONEY_TASK": "There are numbers of events to get free money. You don't need to save money,you can make money without investing. Got for it!",
  "INSTALL_APP": "Add to the home screen",
  "PLEASE_CHECK_NETWORK": "Load failed,please check the network connection",
  "INSTALLED_SUCCESSED": "Installation successful,please check your home screen",
  "BROWSER_NOT_SUPPORT": "The current browser doesn't support,please use Chorme broswer",
  "INVITE_FRIEND_DO_TASK_TOGETHER": "Invite friends to take assignments together",
  "ENJOY_FRIEND_YEAR_PROFIT": "Enjoy 20% of your friends'assignment income",
  "INVITE_FRIEND": "Invite friends",
  "FRIEND_FINISH_TASH": "Friends complete assignments",
  "GET_AWARD": "Get a reward",
  "INVITE_NOW": "Invite now",
  "MY_TEAM": "My team",
  "INVITE_AMOUNT": "Friends num",
  "TOTAL_PROFIT": "Accumulated earnings",
  "INVITE_RULE": "Invite rules",
  "SHARE_AD_GET_CASH": "Earn instant cash from assignments",
  "MAKE_MONEY_NOW": "Make money now",
  "SELECT_VIP_LEVEL": "Select VIP level",
  "TASK_PACKAGE": "Package",
  "N_TIMES": "{0} times",
  "PACKAGE_NUM": "Number of packages",
  "SELECT_BUY_TIME": "Select the duration of purchase",
  "AVAILABLE": "Available",
  "NEED_PAY": "To pay",
  "BUY_NOW": "Buy now",
  "BUY_SUCCESS": "Purchased successfully",
  "BUY_N_SUCCESS": "You successfully purchased {0}!",
  "BUY_FAILED": "Purchase failed",
  "ACCOUNT_SHORT_BALANCE": "Account available balance insufficient",
  "TO_DEPOSIT": "To deposit",
  "CLICK_ABOVE_MAKE_MONEY": "Earn 1000 per day easily, get free money for 100 years",
  "START_MAKE_MONEY_FREE": "Starts making money for free now",
  "VIP_CENTER": "Member center",
  "HELLO_VIP_N": "Has purchased VIP{0}!",
  "OWEN_DAY_TASK_AMOUNT": "Daily assignments",
  "NOT_BUY_VIP_N": "Has not purchased VIP{0}",
  "DO_TASK_LEVEL": "Assignment level",
  "VIP_N_AND_BELOW": "VIP {0} and below",
  "DAY_TASK_NUM": "Assignment times per day",
  "PREDICT_DAY_PROFIT": "Estimated daily earnings",
  "PREDICT_TOTAL_PROFIT": "Estimated total revenue",
  "N_DAY": "{0} days",
  "EACH_DAY": "Every day",
  "DO_TASK_NOW": "Take assignments to make money now",
  "ABOUT_US": "About us",
  "SEE_MORE": "Read more",
  "DAY_DATA": "Daily data",
  "TODAY_PROFIT": "Cumulative return",
  "TODAY_TASK": "Friends num",
  "TASK_DATA": "Assignment",
  "FREE_TASK_COUNT": "Free assignment times",
  "TASK_COUNT": "Assignment times",
  "YOU_NOT_BUY_VIP": "You haven't been VIP yet",
  "RECOMMEND_TASK": "Recommend",
  "MORE_TASK": "More assignments",
  "MESSAGE_CENTER": "Notifications",
  "READ_ALL": "All read",
  "HELP_CENTER": "Help center",
  "MY_VIP": "My VIP",
  "BUY_AGAIN": "Overlay purchase",
  "NOT_BUY_VIP": "No membership",
  "TASK_LEVEL": "Acceptable assignment levels",
  "NOT_BUY": "Have not purchased",
  "RULES_AND_DESC": "Rules and instructions",
  "GET_MORE_PROFIT": "Earn more revenue",
  "MY_WALLET": "My wallet",
  "WALLET_HISTORY": "Transaction log",
  "ACCOUNT_BALANCE": "Account balance",
  "WITHDRAW_WEB": "Withdrawal",
  "TOTAL_EARNINGS": "Cumulative income",
  "DEPOSIT_WEB": "Deposit",
  "MY_TASKS": "My assignment",
  "ALL_TASKS": "All assignments",
  "INPROGRESS": "Pending",
  "CHECKING": "Viewing",
  "FINISHED": "Completed",
  "BUY_VIP_GET_MORE_PROFIT": "To be members to receive exclusive and expensive assignment tasks",
  "HIGH_LEVEL_HIGH_GAINED": "The higher the level, the more you earn",
  "INVITE_FRIEND_TOGETHER": "Invite friends to earn together",
  "RANKING": "Ranking",
  "CONTACT_US": "Contact support",
  "HELP": "Help center",
  "TASK_CENTER": "Assignments",
  "MY_TASK": "My assignment",
  "ALL": "All",
  "FREE": "Free",
  "I_SEE": "I see",
  "TASKS_GUIDE_TITLE1": "You can view different levels of assignment assignments here",
  "TASKS_GUIDE_DESC1": "The higher the level of assignment task, the more generous the reward",
  "TASK_DETAIL": "Assignment details",
  "TASK_AWARD": "Assignment income",
  "TOTAL_TASK": "Total number of assignments",
  "REST_TASK": "Number of remaining assignments",
  "TASK_TIME": "Assignment task time",
  "TASK_IS_ENDED": "Assignment mission has ended",
  "TASK_DESC": "Assignment task description",
  "TASK_REQUIREMENTS": "Assignment requirements",
  "TASK_REQUIREMENTS_CONTENT_N_CLICK": "When {0} valid friends click the link to complete the task, the reward will be automatically distributed to your account",
  "TASK_STEPS": "Assignment task steps",
  "CLICK_RECEIVE_TASK": "Click the down button to start the assignment",
  "HAS_RECEIVED": "Is assigning ",
  "COPY_SHARE_TEXT": "Copy your exclusive representative words",
  "MANUAL_CONTROL_TO_SHARE": "To share manually or click on WhatsApp, Facebook and other one-button share icon.",
  "CLICK_TO_QUICK_SHARE": "Click on the icon to quickly share it with friends",
  "TASK_AUTO_FINISHED_N_FRIEND": "After sharing, {0} friends click to watch, you can automatically get the bonus.",
  "TASK_END_COUNT_DOWN": "Mission end countdown",
  "CAN_GET_AWARD": "Bonuses available",
  "TIP_LET_YOUR_FRIEND_CLICK_YOUR_LINK": "Tip: Ask your friends to quickly browse the links you shared to get a quick bonus",
  "DO_OTHER_GET_MORE_PROFIT": "I want to take assignments for more brands",
  "RECEIVE_SUCCESS": "Assignment mission began",
  "FINISHED_TASK_CAN_GET_N": "Complete assignment task to get {0}",
  "CONTINUE": "Continue",
  "SO_SORRY": "Sorry",
  "CURRENT_TASK_ONLY_VIP_N": "Upgrade to LV {0} to take assinment for the brand",
  "UPGRADE_VIP_N_GET_MORE_MONEY": "Immediately gain the qualification of Lv{0}",
  "TASK_COUNT_SHORT": "Insufficient number of tasks to assignment",
  "TASK_COUNT_SHORT_THAN_CONTINUE": "Insufficient number of tasks to assignment,the number of purchases continues",
  "BUY_COUNT": "The number of purcahse",
  "TASK_EXPIRED": "Assignment timeout",
  "PLEASE_FINISH_TASK_ON_TIME": "Please finish the assignment within the specified time",
  "RECEIVE_AGAIN": "Accept the assignment again",
  "NOT_TASK": "This brand is not available",
  "NEXT": "Next",
  "PREVOUS": "Last",
  "JUMP": "Skip",
  "TASK_DETAIL_GUIDE_TITLE1": "Here is the number of assignment and rewards",
  "TASK_DETAIL_GUIDE_TITLE2": "Step 1, click the button to get the assignment assignment",
  "TASK_DETAIL_GUIDE_TITLE3": "Step 2",
  "TASK_DETAIL_GUIDE_TITLE4": "Step 3, share your exclusive assignment message with your friends through social media software (just paste it).",
  "TASK_DETAIL_GUIDE_TITLE5": "There is a time limit for the assignment!' Ask {0} friends to click the link to help you become an ambassador, you can get your endorsement award for free",
  "OFFICIAL_ACCOUNT": "Bank transfer official designated account",
  "RECEIVER_NAME": "Receiver name",
  "RECEIVER_ACCOUNT": "Receiver account",
  "RECEIVER_BANK": "Full name of the bank",
  "UPLOAD_TIP": "Please remit the money according to the above information and keep the screenshot of the remittance. After the remittance is successful, it will be submitted for review in the recharge record. The minimum remittance amount is {0}.",
  "FILL_USER_INFO": "Fill in user information",
  "FULLNAME_OF_BANK": "Full name of the bank",
  "ENTER_FULLNAME_OF_BANK": "Please fill in the full name of the bank",
  "TRANSFER_NAME": "Remitter name",
  "ENTER_TRANSFER_NAME": "Please fill in the name of remitter",
  "TRANSFER_ACCOUNT": "Remitter account",
  "ENTER_TRANSFER_ACCOUNT": "Please fill in the remitter account",
  "TRANSFER_AMOUNT": "The amount of remittance",
  "ENTER_TRANSFER_AMOUNT": "Please fill in the amount of remittance",
  "TRANSFER_TIME": "Remittance time",
  "SELECT_TRANSFER_TIME": "Please fill in the remittance time",
  "TRANSFER_CERTIFICATION": "Payment document",
  "SEE_DEMO": "Check the sample",
  "SUBMIT_USER_INFO_CERTIFICATION": "Submit the transfer voucher",
  "SUBMIT_SUCCESS": "Submitted successfully",
  "ABOUT_5_MINS_ARRIVE": "It is expected to arrive in 1-5 minutes, please wait patiently",
  "CONTACT_CUSTOM_SERVICE_QUICKLY": "Contact support for quick verification",
  "SEE_DEPOSIT_DETAIL": "Check your account statement",
  "BANK_CHANNEL_UNAVAILABLE": "Bank account transfer temporarily unavailable",
  "ENTER_TRANSFEROR_NAME_AGAIN": "Please re-enter your remitter name",
  "ENTER_TRANSFEROR_ACCOUNT_AGAIN": "Please re-enter your remitter account number",
  "TRANSFER_AMOUNT_CANT_LESS_THAN_MIN": "Remittance amount shall not be less than {0}",
  "ORDER_DETAIL": "The order details",
  "ORDER_PAYING": "The order is processing",
  "PLEASE_WAIT": "Please wait for a while",
  "BACK_HOME": "Back to the home page",
  "QUERYING_ORDER": "Checking the order",
  "SEARCH_ORDER_NO_RESULT": "No order has been found, please try again later",
  "HISTORY": "Record",
  "SELECT_PAYMENT": "Select the deposit way",
  "DEPOSIT_AMOUNT": "Deposit amount",
  "ENTER_DEPOSIT_AMOUNT": "Enter the deposit amount",
  "PAY_NOW": "Pay now",
  "HOW_TO_PAY": "How to pay",
  "SELECT_BANK": "Select Bank",
  "MIN_DEPOSIT": "Minimum",
  "MAX_DEPOSIT": "Maximum",
  "NO_DEPOSIT_CHANNEL": "No deposit channels avaliable",
  "NO_QUICK_CHANNEL": "No quick payments channels avaliable",
  "MIN_DEPOSIT_N": "The minimum amount is {0}",
  "MAX_DEPOSIT_N": "The maximum amount is {0}",
  "PROFIT_RANKING": "Revenue ranking",
  "SUCCESS_DEPOSIT_IN_N_TO_BALANCE": "Successful deposit the balance of {0}",
  "FINISH": "Complete",
  "DEPOSIT_FAILED": "Deposit failed",
  "DEPOSIT_NOT_ARRIVE": "The deposit is not received",
  "CONTACT_CS": "Contact support",
  "LATEST_3_MONTH": "Records for the last three months",
  "PROMOTE_BEGINNER_DESC": "Take the assignment of a brand can get $20, low threshold, fast withdrawal",
  "HAS_BEEN_CLAIMED": "Has been claimed",
  "N_USER_JOINED": "Has participated",
  "PEOPLE": "people",
  "ENTER_YOUR_TELEPHONE": "Please enter your telephone",
  "SET_YOUR_PASSWORD": "Set your account password",
  "GET_CASH_NOW": "Receive cash immediately",
  "REG_NOW_GET_MONEY": "Start receive money immediately",
  "IS_GETTING": "Receiving",
  "TEAM_MEMBERS": "Friends num",
  "TOTAL_CONTRIBUTE": "The cumulative contribution",
  "TEAM_LIST": "Team list",
  "N_LEVEL_FRIEND": "Friend of level {0}",
  "CONTRIBUTE_AMOUNT": "Contribution amount",
  "CAN_NOT_WITHDRAW_WAIT": "Can't withdraw at the moment,please wait",
  "BACK": "Return",
  "WITHDRAW_AMOUNT": "Amount",
  "AVAILABLE_BALANCE": "Avaliable",
  "ENTER_WITHDRAW_AMOUNT": "Please enter the withdrawal amount",
  "SELECT_WITHDRAW_WAY": "Select the withdrawal way",
  "MIN_WITHDRAW": "Minimum",
  "MAX_WITHDRAW": "Maximum",
  "WITHHDRAW_FEE": "Withdrawal commission",
  "TOTAL_DEDUCE_AMOUNT": "Total amount of deduction",
  "NEXT_STEP": "Next",
  "ESTIMATED_ARRIVE": "The withdrawal will be arrive in 1 to 5 minutes,please wait!",
  "WITHDRAW_SURE": "Withdrawal confirmation",
  "WILL_DEDUCE_N_GIFT_MONEY": "{0} reward money will be deducted",
  "GIFT_BALANCE": "The balance of the gift money",
  "AFTER_RECEIVE_TASK_N_HOURS": "After starting the endorsement task, please share within {0} hours, and click the button below to copy"
}
`);

      for (let k of Object.keys(lang_map)) {
        this.$http.post('v1/updateLang',{
          slug: k,
          content: lang_map[k],
          local: 'EN'
        }).then(res=>{

        }).catch(err=>{
          console.log('update failed:',err)
        })
      }
    }
  }
}
</script>

<style lang="scss">
.tool-page {
  min-height: 100vh;
}
</style>